language: cpp

compiler:
  - gcc
  - clang
os:
  - linux
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - clang-3.7
      - g++-5
      - gcc-5

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake
    fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - if [ ${CXX} = 'clang++' ]; then export CXX='clang++-3.7'; fi
  - if [ ${CXX} = 'g++' ]; then export CXX='g++-5'; fi

script:
  - mkdir build
  - cd build
  - cmake .. && make
